/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package trocacartoesutf;

import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import static trocacartoesutf.ColImpl.TransacaoMap;
import trocacartoesutf.gerente.ColecionadorGer;
import static trocacartoesutf.gerente.GerImpl.listaColecionadores;

/**
 *
 * @author MAYKO
 */
public class EstadoTransacoesView extends javax.swing.JDialog {
    DefaultTableModel model = new DefaultTableModel();
    Integer id = 0;

    /**
     * Creates new form tabela
     */
    public EstadoTransacoesView(java.awt.Frame parent, boolean modal) {
        
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        carregaCabecalho();
    }
    
    private void carregaCabecalho(){
        Vector<String> col = new Vector();
        col.add ("Id");
        col.add("Estado");
        model.setDataVector(null, col);
        carregaDados();
    }
    
    private void carregaDados(){
        int i = 0;
        String status = "";
        
        for(Transacao transacao: ColImpl.listaTransacao){
            switch(transacao.getStatus()){
                case 1:
                    status = "ATIVADO";
                    break;
                case 2:
                    status = "FALHADO";
                    break;
                case 3:
                    status = "ABORTADO";
                    break;
                case 4:
                    status = "EFETIVADO TEMP.";
                    break;
                case 5:
                    status = "EFETIVADO";
                    break;
            }

            model.addRow(new Object[]{transacao.getId(),status});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTbUf = new javax.swing.JTable();
        OK = new javax.swing.JButton();
        CANCELAR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTbUf.setModel(model);
        jScrollPane1.setViewportView(jTbUf);

        OK.setText("Ok");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        CANCELAR.setText("Cancelar");
        CANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELARActionPerformed(evt);
            }
        });

        jLabel1.setText("Consulta Estado de Transações:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(OK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CANCELAR))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(67, 67, 67)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OK)
                    .addComponent(CANCELAR))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        // TODO add your handling code here:
//        id = MyNumber.parseInt(model.getValueAt(jTbUf.getSelectedRow(), 0));
        //System.out.println(id);
        dispose();
    }//GEN-LAST:event_OKActionPerformed

    public Integer getId(){
        return id;
    }
        
    
    private void CANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELARActionPerformed
        // TODO add your handling code here:
        id = 0;
        dispose();
    }//GEN-LAST:event_CANCELARActionPerformed

    public void Limpar() {
//        jtfConsulta.setText("");
//        jtfCpf.setValue(null);
        int contRow = model.getRowCount();
        for (int i = 0; i < contRow; i++) {
            model.removeRow(0);
        }
        //}
        //Retirar = 0;
    }
    
    private void carregaDados(String nome){
//        Limpar();
//        nome = nome.toUpperCase();
//        Session session = HibernateUtil.getSession();
//        //Query q = session.createQuery("from Aluno a where a.nome = ?");
//        Query q = session.createQuery("from Produtor p where upper(p.nome) like ?");
//        q.setString(0,"%" + nome + "%");
//        //q.setString(0, nome);
//        List<Produtor> list = q.list();
//        for (Produtor produtor : list) {
//            model.addRow(new Object[]{
//                produtor.getIdprodutor(),
//                produtor.getNome(),
//                produtor.getCpf(),
//                produtor.getMunicipioIdmunicipio().getUfIduf(),
//                produtor.getMunicipioIdmunicipio()                
//            });
//        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstadoTransacoesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstadoTransacoesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstadoTransacoesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstadoTransacoesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                EstadoTransacoesView dialog = new EstadoTransacoesView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CANCELAR;
    private javax.swing.JButton OK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTbUf;
    // End of variables declaration//GEN-END:variables
}
